### ISSUE TITLE
Animation lock \ touch area

### ISSUE THREAD

**Issue by NeoDigi** [vpaliyX/LoginConcept#3]
Hey really cool project, but I feel like there are 2 key point that could be improved:
- When you click on the vertical text to switch the view, if you click anywhere fast enough, the animation will stop midway and the views will just be stuck somewhere in the middle (it doesn't crash the app, and it easy to get the view back to normal, but still)

- I think it would be better if not only the vertical text was clickable but the whole side

What do you think ?

**Comment by vpaliy** [comment]
That's a good point! Thanks for that.
I am going to update the project tonight. In order to implement the second point we just need to change this ![line](https://github.com/vpaliyX/LoginConcept/blob/master/app/src/main/java/com/vpaliy/loginconcept/AuthFragment.java#L61) to `@OnClick(R.id.root)` and that's it. However, I'm not sure 100% that we don't get any side effects from doing so. Anyways, I will try this in a few hours. 

Thanks for the points!

**Comment by vpaliy** [comment]
All the points above have been brought to life. Check out my last commits.
